---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-crud-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-crud-k8s
    spec:
      containers:
        - name: springboot-crud-k8s
          image: springboot-crud-k8s:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: db-config
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: dbname
                  name: db-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: db-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: springboot-crud-k8s
  type: NodePort
